### PR TITLE
BlockedUsers unable to see about info and avatar

### PR DESCRIPTION
**Pull request by amir10058**
related: #561

### CODE REVIEW

**Comment by ex3ndr** [comment]
LGFM
@rockjam can you review it?

**Comment by ex3ndr** [comment]
But i feel that it have some performance problems as loading blocked list will block current thread, isn't it?

**Comment by rockjam** [comment]
@ex3ndr @amir10058 will take a look today

**Comment by amir10058** [comment]
@rockjam i just improve the performance that @ex3ndr mentioned, only one query executed during initialize step.

**Pull request closed without merging**
