### PR TITLE
Remove scalaz from project dependencies

### PR DESCRIPTION
**Pull request by rockjam**
Remove scalaz from project dependencies, as we used only small part of it. Was easily replaceable by cats.

### CODE REVIEW

**Comment by rockjam** [comment]
Don't merge. Need to figure out problems related to cats upgrade

**Comment by prettynatty** [comment]
There is also dependency on scalaz in the configs library.

**Comment by rockjam** [comment]
Downgraded cats to 0.3.0 - solved problem with `DefClassNotFound`

**Comment by rockjam** [comment]
Didn't find scalaz in sbt `dependencyTree` report. What configs did you mean?

**Pull request merged**
