### PR TITLE
Bugfix/njv 227 dont create main activity in forwards

### PR DESCRIPTION
**Pull request by paykoob**
when app is in MainActivity, if we press back, usually app should be closed.
but if we forward some message, we get back to original dialog.
this is because app starts new MainActivity in forwards.

-- 
I fix a unrelated minor cast in runtime too

### CODE REVIEW

**Comment by kor-ka** [comment]
Thanks for contribution!
But this fix does not cover one case: when app is not started and ChatActivity is launched from notification(shown by push) we have no activity stack, so if you'll try to forward message it will just close app.
This problem happens because app is not launching main activity before ChatActivity in this case. So we can't accept this commit until it will be fixed (It's in my road map, i'm going to fix using CLEAR_TOP flag for main activity)

**Comment by paykoob** [comment]
@kor-ka i push new commit, is it everything covered?

**Comment by kor-ka** [comment]
Yes, it's now ok, one more [thing](https://github.com/paykoob/actor-platform/commit/eb6baad42cd8dd71872e795c2be471c47fa353e8#diff-bf6c34714f6597d44163f39fca9fd76bR457)

**Comment by paykoob** [comment]
but if we are top (there is no previous mainActivity in stack when app has been started from push notifications) we'll remain in activity stack.
and activity dose not close. then in onBackPressed in MainActivity we return to origin dialog.

**Pull request merged**
