### PR TITLE
re-format doc files

### PR DESCRIPTION
**Pull request by morya**
I am new to this project, are there any other detailed documents?
IMMO, these docs are not enough for beginners like me...

### CODE REVIEW

**Comment by ex3ndr** [comment]
Thank you! Regarding your question: we are not focused on documentation yet as we need(want) to provide more features first.

**Comment by rockjam** [comment]
@morya You'd better ask questions about actor platform in our open source group. You can join it via this link: https://quit.email/join/c21f58a5576bfe8c81625f6b2d1a2a59c95966e418b6ceb0da4d06b90e8aa536
This way you can get faster feedback, ask some questions if you are stuck

**Comment by morya** [comment]
thanks, I found this link is quite useful.

https://developer.actor.im

**Comment by rockjam** [comment]
@morya That's great :+1:

**Pull request merged**
