### PR TITLE
Feature/njv 325 localize grouptopic and groupabout

### PR DESCRIPTION
**Pull request by paykoob**
https://github.com/actorapp/actor-platform/issues/540

### CODE REVIEW

**Comment by ex3ndr** [comment]
Reject. New service messages that are not implemented on Server.

**Comment by paykoob** [comment]
GroupTopic and GroupAbout are implemented on server @ex3ndr!!
those are in "GroupServiceMessages":
```
package im.actor.server.group

import im.actor.api.rpc.files
import im.actor.api.rpc.messaging._

object GroupServiceMessages {
  def groupCreated = ApiServiceMessage("Group created", Some(ApiServiceExGroupCreated))
  def userInvited(userId: Int) = ApiServiceMessage("User invited to the group", Some(ApiServiceExUserInvited(userId)))
  def userJoined = ApiServiceMessage("User joined the group", Some(ApiServiceExUserJoined))
  def userLeft(userId: Int) = ApiServiceMessage("User left the group", Some(ApiServiceExUserLeft))
  def userKicked(userId: Int) = ApiServiceMessage("User kicked from the group", Some(ApiServiceExUserKicked(userId)))
  def changedTitle(title: String) = ApiServiceMessage("Group title changed", Some(ApiServiceExChangedTitle(title)))
  def changedTopic(topic: Option[String]) = ApiServiceMessage("Group topic changed", Some(ApiServiceExChangedTopic(topic)))
  def changedAbout(about: Option[String]) = ApiServiceMessage("Group about changed", Some(ApiServiceExChangedAbout(about)))
  def changedAvatar(avatar: Option[files.ApiAvatar]) = ApiServiceMessage(
    "Group avatar changed",
    Some(ApiServiceExChangedAvatar(avatar))
  )
}

```

but I18Engine just ignores them and show the original message of server (English)

**Comment by paykoob** [comment]
this issue has been implemented in  our version and works well!

**Comment by ex3ndr** [comment]
Yes, but they are not generated on it and not stored in conversation history

**Comment by paykoob** [comment]
yes, but consider this situation:

Alice is offline and bob creates the group with her, and after creating changes the about, then alice going online.

oops! she see this ApiServiceMessage in her history: "Group About Changed"

I can add the Message to ConversationHistory (just like title changed, with some schema changes for UpdateGroupAboutChanged).

another option is just ignoring these ServiceContents on core.

**Comment by paykoob** [comment]
screenshot from 2016-04-12 12 48 23

**Pull request merged**
